/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dictionary.h"

bool_t
xdr_word (XDR *xdrs, word *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 255))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_WORD (XDR *xdrs, WORD *objp)
{
	register int32_t *buf;

	 if (!xdr_word (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_word (xdrs, &objp->meaning))
		 return FALSE;
	return TRUE;
}
