/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RING_H_RPCGEN
#define _RING_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define RING_PGM 0x31234567
#define RING_PGM_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define send 1
extern  void * send_1(int *, CLIENT *);
extern  void * send_1_svc(int *, struct svc_req *);
#define aliveMessage 2
extern  void * alivemessage_1(void *, CLIENT *);
extern  void * alivemessage_1_svc(void *, struct svc_req *);
extern int ring_pgm_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define send 1
extern  void * send_1();
extern  void * send_1_svc();
#define aliveMessage 2
extern  void * alivemessage_1();
extern  void * alivemessage_1_svc();
extern int ring_pgm_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RING_H_RPCGEN */
